### PR TITLE
Added setup.sh

### PR DESCRIPTION
**Pull request by hexahigh**
Added script that installs all dependencies using apt

### CODE REVIEW

**Comment by alisinabh** [comment]
Thank you for your contribution @hexahigh 

A configuration/setup script can be really helpful. IMO it needs to factor-in the different environments that users might have and continue the setup for their environment. Like what would happen if somebody using fedora, arch or even Windows would run this script?

I think it would be a good addition if it takes into account the environment (operating system and version) and handles the setup procedure based on that. Would you like to extend your script to support this?

**Comment by hexahigh** [comment]
Yeah, i can update it soon when i get time.

**Comment by hexahigh** [comment]
I have updated it and it will now ask the user what package manager they are using and install based on that.
I dont know if the pacman one works as i dont have arch linux.
I will add more package managers when i get the the time to do so.

**Comment by hexahigh** [comment]
I also dont see a point in adding windows as the program doesnt work on windows when i tried it

**Comment by hexahigh** [comment]
Added yum

**Comment by alisinabh** [comment]
Sorry I somehow didn't receive any emails regarding this.

I have added some tiny improvements. Thank you for your contribution.

💚 💙 🧡 ❤️

**Pull request merged**
